task:
  freebsd_instance:
    matrix:
      - image_family: freebsd-15-0-amd64-ufs
  install_script: pkg install -y cmake
  script:
    - cmake -B build -DLIBDEFLATE_BUILD_TESTS=1
    - cmake --build build
    - ctest --test-dir build
    # Direct compilation without official build system
    - cc -O2 -Wall -Werror lib/*.c lib/*/*.c programs/gzip.c programs/prog_util.c programs/tgetopt.c -o libdeflate-gzip
